# Generated by Django 2.1.3 on 2018-12-04 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(max_length=500, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryPlanning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.FloatField(default=0, verbose_name='Budget')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appBudget.Category',
                                               verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.FloatField(default=0, verbose_name='Budget')),
                ('date_start', models.DateField(verbose_name='Start date')),
                ('date_end', models.DateField(verbose_name='End date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                           verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='PlanningExpenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0, verbose_name='Amount')),
                ('date', models.DateField(verbose_name='Date')),
                ('description', models.TextField(max_length=500, verbose_name='Description')),
                ('category_planning',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appBudget.CategoryPlanning',
                                   verbose_name='Category Planning')),
            ],
        ),
        migrations.AddField(
            model_name='categoryplanning',
            name='planning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appBudget.Planning',
                                    verbose_name='Planning'),
        ),
        migrations.AddField(
            model_name='categoryplanning',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                    verbose_name='User'),
        ),
    ]
